import { Check, db, Template } from "astro:db";
import type { template } from "../src/base";

export const templates: template[] = [
    {
        id: "kcc",
        revision: "0.8",
        created_at: new Date("2025-03-25T10:30:00.000Z"),
        type: "full",
        name: "Classic",
        data: {
            kinks: [
                ["General", [
                    ["Fellatio/Blowjobs", ["receive", "give"], 0, "giver sucks receiver's penis"],
                    ["Cunnilingus", ["receive", "give"], 1, "giver licks receiver's vagina"],
                    ["Face-Fucking", ["give", "receive"], 2, "giver thrusts their penis in and out of reciver's mouth in quick manner"],
                    ["Face-Sitting", ["top", "bottom"], 3, "top sits on bottom's face"],
                    ["Handjobs", ["give", "receive"], 4, "giver squeezes, tuggs or strokes the recivcer's penis"],
                    ["Frotting/Scissoring", [""], 98, "rubbing genitals together / on each other"],
                    ["Vaginal Penetration", ["top", "bottom"], 97, "top penetrates the bottoms vagina"],
                    ["Vaginal Fingering", ["give", "receive"], 5, "reciver's vagina is stimulated by using the giver's fingers"],
                    ["Vaginal Fisting", ["give", "receive"], 6, "giver's inserts their hand into the revicer's vagina"],
                    ["Rough Sex", [""], 7, "having sex in rough manner"],
                    ["Creampie", ["give", "receive"], 8, "giver cums in receiver's ass or vagina"],
                    ["Swallowing", ["give", "receive"], 9, "receiver swallows the giver's cum"],
                    ["Facials", ["give", "receive"], 10, "giver cums on receiver's face"],
                    ["Masturbation", ["top", "anal/…"], 11], // to be clarified in the future
                    ["Anal Penetration", ["top", "bottom"], 12, "top penetrates the ass"],
                    ["Anal Fingering", ["top", "bottom"], 13,"reciver's ass is stimulated by using the giver's fingers"],
                    ["Anal Fisting", ["top", "bottom"], 14, "giver's inserts their hand into the revicer's ass"],
                    ["Pegging", ["top", "bottom"], 15, "top anally penetrates bottom with a strap-on"],
                    ["Anilingus/Rimming", ["receive", "give"], 16, "bottom licks top's asshole"],
                ]],
                ["BDSM", [
                    ["Little/Daddy*Mommy", ["dom", "sub"], 17, "dom takes care of the sub, wanting to be caring and provide him with a safe environment"],
                    ["Slave/Master*Mistress", ["dom", "sub"], 18, "dom will train the sub to serve them in the way they enjoy. This will include domestic chores and service as well as sexual and kink aspects of their lives."],
                    ["Pet/Owner", ["dom", "sub"], 19, "dom owns, cares for, and trains the sub; this can take place within the context of pet play or in a non-sexual context"],
                    ["Power Exchange (24/7)", ["dom", "sub"], 22, "dom controls aspects of sub's everyday life"],
                    ["Humiliation/Embarrassment", ["dom", "sub"], 23, "dom humiliates and/or embarrasses the sub"],
                    ["Degradation/Name Calling", ["dom", "sub"], 24, "dom degrades the sub and/or calls the sub names, like \"slut\" "],
                    ["Bondage", ["dom", "sub"], 25, "dom ties sub up"],
                    ["Encasement/Cages", ["dom", "sub"], 26, "dom completely encases the sub in various materials and/or places the sub in a cage"],
                    ["Discipline", ["dom", "sub"], 27, "dom disciplines the sub through training and punishment"],
                    ["CNC/Rapeplay", ["dom", "sub"], 28, "any scene where sub is unable to or does not give consent, that has been properly pre-negotiated"],
                    ["Kidnapping", ["dom", "sub"], 29, "dom kidnappes the sub, in a scenario that has been pre-negotiated"],
                    ["Spanking", ["give", "receive"], 30, "giver hits receiver's ass"],
                    ["Hair Pulling", ["give", "receive"], 101, "giver pulls and guides the reciver bytheir hair"],
                    ["Forced Orgasms", ["give", "receive"], 31, "giver brings the receiver to orgasm through various forms of stimulation"],
                    ["Orgasm Denial", ["dom", "sub"], 32, "sub is not allowed to cum, unless dom allows them to"],
                    ["Chastity", ["dom", "sub"], 33, "dom locks up sub's genitals"],
                    ["Masturbation Instructions", ["give", "receive"], 34, "giver gives instructions on how the receiver should masturbate"],
                    ["Servitude", ["dom", "sub"], 35, "sub serves dom's needs (not only sexually)"],
                    ["Sensation Play", ["dom", "sub"], 36, "sensory stimulation with sight, sound, touch, taste, and smell"],
                    ["Electric Stimulation", ["dom", "sub"], 37, "dom uses electricity to stimulate the sub"],
                    ["Breathing Play", ["dom", "sub"], 38, "dom restricts sub's breathing"],
                    ["Choking", ["dom", "sub"], 39, "sub gets chocked by the dom"],
                    ["Gags", ["dom", "sub"], 40, "anythings involving ball gags or other gags"],
                    ["Begging", ["dom", "sub"], 41, "sub beggs to the dom"],
                    ["Teasing", ["dom", "sub"], 42, "dom teases the sub in often mean way"],
                    ["Worship", ["dom", "sub"], 44, "sub worships the dom's body"],
                    ["Sounding/Urethral Insertion", ["dom", "sub"], 43, "dom inserts something in sub's uretha"],
                ]],
                ["Kinks", [
                    ["Incest", ["cousins", "siblings"], 45, "sexual interactions with close relatives"],
                    ["Incest (any age)", ["parents", "children"], 46, "sexual interactions with close relatives of any age"],
                    ["Impregnation/Pregnancy", ["top", "bottom"], 47, "top tries to impregnate bottom, bottom is pregnant, etc"],
                    // TODO: rename big time
                    ["Milking", ["dom", "sub"], 48, "dom milks the sub penis or breasts"],
                    ["Nursing", ["dom", "sub"], 49, "dom \"breast-feeds\" sub"],
                    ["Feet", [""], 50, "anything involving and having a focus on feet"],
                    ["Pee", ["dom", "sub"], 51, "dom pees on sub"],
                    ["Roleplay", [""], 52, "Roleplaying a scenario with predefined personalties"],
                    ["Diapers/ABDL", [""], 53, "interactions with a focus of Diapers"],
                    ["Cheating/Cuckold/NTR", ["dom", "sub"], 54, "dom \"cheats on\" sub in a degrading/etc way"],
                    ["Feminization/Sissy", ["dom", "sub"], 55, "dom feminizes the sub, by making the sub wear makeup and/or woman clothes"],
                    ["Exhibition/Voyeur", ["exhib", "voyeur"], 56, "exhibtor shows off their naked body, while the voyeur watches (openly or in secret)"],
                    ["Double-Penetration/Spitroasting", ["top", "bottom"], 57, "top or tops penetrate more than 1 holes of the bottom"],
                    ["Multi-Partner", ["top", "bottom"], 58, "having multiple partners during a scenario"],
                    ["Tickling", ["give", "receive"], 59, "giver tickles the receiver, either lighty or more intensive"],
                    ["Cumswapping", [""], 60, "french kissing with cum"],
                    ["Thighsex", ["top", "bottom"], 61, "top gets of the sub using their thighs"],
                    ["Titfuck", ["top", "bottom"], 62, "top gets of the sub using their breats"],
                    ["Footjob", ["give", "receive"], 63, "top gets of the sub using their feet"],
                    ["Armpit Sex", ["top", "bottom"], 64, "top gets of the sub using their armpit"],
                    ["Smoking", [""], 99, "anything involing Smoking"],
                ]],
                ["Pain", [
                    ["Physical Pain", ["give", "receive"], 65, "giver inflicts pain on the body of the receiver"],
                    ["Nipple Clamps", ["give", "receive"], 66, "giver uses nipple Clamps on the body of the receiver"],
                    ["Hard Spanking", ["give", "receive"], 67, "The giver gives the recipient a sharp slap"],
                    ["Whipping", ["give", "receive"], 68, "giver whips the receiver with a whip"],
                    ["Slapping", ["give", "receive"], 69, "giver slaps the receiver, for example across the face"],
                    ["Biting", ["give", "receive"], 70, "giver bites the receiver, leaving bite marks"],
                    ["Hot Wax", ["give", "receive"], 71, "giver pours molten wax over the receiver's body"],
                    ["Scratching", ["give", "receive"], 72, "giver scratches the receiver's body leaving scrathmarks"],
                    ["Cock/Ball Slapping", ["give", "receive"], 73, "giver slaps the cock and/or balls of the receiver"],
                    ["Vagina Slapping", ["give", "receive"], 74, "giver slaps the vagina of the receiver"],
                    ["Clothespins", ["give", "receive"], 75, "giver pins clothepins on the receiver's body"],
                    ["Needles", ["give", "receive"], 76, "giver inserts needles into the body of the receiver"],
                ]],
                ["Clothing", [
                    ["Clothed Sex", [""], 77, "sexual interactions with as many clothes on as possible"],
                    ["Collars", ["dom", "sub"], 78, "sub wears a collar, which might have a leash for dom to pull on"],
                    ["Lingerie", [""], 80, "interactions are done with lingerie on"],
                    ["Stockings/Pantyhose", [""], 81, "wearing Stockings or aPantyhose during interactions"],
                    ["Crossdressing", [""], 82, "to wear clothing typically worn by the opposite sex"],
                    ["Forced Dressup", ["dom", "sub"], 83, "dom dicates/forces the sub to wear specific clothes"],
                    ["Leather", [""], 84, "Leather is the main focus of the clothing"],
                    ["Latex", [""], 79, "Latex is the main focus of the clothing"],
                    ["Socks", [""], 85, "the socks stay on"],
                    ["Uniforms", [""], 86, "wearing uniforms, like police or nurses"],
                    ["Cosplay", [""], 87, "wearing a cosplay during interactions"],
                    ["Furry", [""], 88, "wearing parts or complete fursuit during interactions"],
                ]],
                ["Extreme", [
                    ["Scat", [""], 89, "anything involving feces"],
                    ["Vomit", [""], 100, "anything involving vomit"],
                    ["Cutting/Knifeplay", ["give", "receive"], 90, "giver cuts the receiver with a knife"],
                    ["Raceplay", ["dom", "sub"], 91, "dom dominates the sub, on the base of racial stereotypes"],
                    ["Bestiality", [""], 92, "inclusion of animals"],
                    ["Necrophilia", [""], 93, "inclusion of dead bodies"],
                    ["Hard Rape", ["top", "bottom"], 94, "top rapes the bottom"],
                    ["Blood", [""], 96, "interactions with a focus of drawing blood"],
                    ["Cannibalism", ["dom", "sub"], 95, "dom eates the sub's body"],
                    ["Torture", ["dom", "sub"], 20, "dom tortures the sub"],
                    ["Genital Mutilation", ["give", "receive"], 21, "giver mutilates the receivers genitals"],
                ]],
            ],
        },
    },
    {
        id: "april-fools",
        revision: "0.1",
        created_at: new Date("2025-04-01T00:00:00.000Z"),
        type: "full",
        name: "AF",
        data: {
            kinks: [
                ["Extreme", [
                    ["Hand Holding", [""], 0],
                    ["Cuddles", [""], 1],
                    ["Making Out", [""], 2],
                    ["Forehead Kisses", ["give", "receive"], 3],
                    ["Hair Playing", ["give", "receive"], 4],
                    ["Paw Frotting", [""], 5],
                    ["Austria", ["top", "bottom"], 6],
                ]],
            ],
        },
    },
    {
        id: "unhealthy-stimming",
        revision: "0.1",
        created_at: new Date("2025-03-25T10:30:00.000Z"),
        type: "full",
        name: "(unhealthy) Stimming & Coping Mechanisms",
        data: {
            kinks: [
                ["Socio-Sexual etc", [
                    ["Oversharing", [""], 4],
                    ["Doomscrolling", [""], 9],
                    ["Dating Apps", [""], 10],
                    ["Isolation", [""], 11],
                    ["Gooning", [""], 13],
                    ["Binge Watching", [""], 14],
                    ["Little Stuff", [""], 15],
                ]],
                ["Self Harm", [
                    ["Cutting", [""], 5],
                    ["Burning", [""], 6],
                    ["Overeating", [""], 7],
                    ["Undereating", [""], 8],
                ]],
                ["Substances", [
                    ["Alcohol", [""], 0],
                    ["Weed", ["smoke", "vape"], 1],
                    ["Weed", ["eat", "bong"], 16],
                    ["Nicotine", ["smoke", "vape"], 2],
                    ["Caffeine", [""], 3],
                    ["Other Drugs/etc", [""], 12],
                ]],
            ],
        },
    },
];

// https://astro.build/db/seed
export default async function () {
    await db.insert(Template).values(templates);
    await db.insert(Check).values([
        {
            id: "test",
            template_id: "kcc",
            template_revision: "0.8",
            created_at: new Date("2025-03-11T08:34:00.000Z"),
            data: { "ratings": [[1, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0], [0, 0], [0], [0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0], [0, 0], [0], [0], [0], [0], [0, 0], [0], [0], [0], [0], [0], [0], [0, 0], [0, 0], [0], [0], [0, 0], [0, 0], [0], [0, 0], [0, 0], [0], [0], [0, 0]] },
        },
    ]);
}
